In [9]:
import numpy as np

In [10]:
print("randint:",np.random.randint(1,10,5))
print("rand:",np.random.rand(5))
print("choice:",np.random.choice([1,2,3,4,5],5))

randint: [5 3 7 5 9]
rand: [0.06505159 0.94888554 0.96563203 0.80839735 0.30461377]
choice: [5 2 4 4 4]


In [11]:
print("randint:",np.random.randint(1,10,5))
print("rand:",np.random.rand(5))
print("choice:",np.random.choice([1,2,3,4,5],5))


randint: [7 8 3 1 4]
rand: [0.18223609 0.75536141 0.42515587 0.20794166 0.56770033]
choice: [5 2 2 4 2]


In [12]:
#with seed - run 1
np.random.seed(42)
print("randint:",np.random.randint(1,10,5))
print("rand:",np.random.rand(5))
print("randint:",np.random.choice([1,2,3,4,5],5))


randint: [7 4 8 5 7]
rand: [0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
randint: [3 5 2 4 2]


In [13]:
# with same seed - run 2
np.random.seed(42)
print("randint:",np.random.randint(1,10,5))
print("rand:",np.random.rand(5))
print("randint:",np.random.choice([1,2,3,4,5],5))
# same output as above cell

randint: [7 4 8 5 7]
rand: [0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
randint: [3 5 2 4 2]


In [28]:
print("randint:",np.random.randint(1,10,5))
print("rand:",np.random.rand(3,10,5))
print("choice:",np.random.choice(['Pranav','ajinkya','shubham'],5))


randint: [3 5 5 5 3]
rand: [[[0.66519722 0.52306542 0.35883048 0.87720054 0.39244511]
  [0.81659944 0.43913491 0.37694443 0.46267979 0.30137787]
  [0.74760938 0.50272039 0.2322127  0.89957457 0.38389122]
  [0.54355286 0.90647211 0.624238   0.11689804 0.93983212]
  [0.62770805 0.33490561 0.13927207 0.79402519 0.62007276]
  [0.53346109 0.89389258 0.78859721 0.15167488 0.31172207]
  [0.24848914 0.74394629 0.03353243 0.56988968 0.76245869]
  [0.87676564 0.34208175 0.8212573  0.11063174 0.84645229]
  [0.12748866 0.39728729 0.79729537 0.14991743 0.2292514 ]
  [0.72225257 0.72003654 0.64114763 0.69394844 0.54272444]]

 [[0.25179906 0.34569599 0.18159772 0.90845056 0.58339179]
  [0.40085142 0.4620058  0.94728334 0.1533514  0.58622983]
  [0.50588868 0.61145424 0.01811018 0.87212391 0.93211828]
  [0.56513318 0.69665082 0.92249938 0.70723863 0.15253904]
  [0.57628836 0.60671505 0.42413067 0.73644424 0.93436701]
  [0.92556851 0.45083937 0.11323805 0.9848412  0.83889809]
  [0.12466268 0.92084188 0.