In [1]:
import numpy as np

In [6]:
arr = np.array([2,1,6,3,9])
lst = [1,2,3,4,5]
print(arr)
print(lst)

array([2, 1, 6, 3, 9])

In [24]:
print(arr+5)
print([x+5 for x in lst])

[ 7  6 11  8 14]
[6, 7, 8, 9, 10]


In [26]:
print(arr*4)
print([x*4 for x in lst])

[ 8  4 24 12 36]
[4, 8, 12, 16, 20]


In [14]:
import time 
start_time = time.time()
print(arr+5)
end_time = time.time()
execution_time = end_time - start_time
print(f'\nExecution time: {execution_time} seconds')

[ 7  6 11  8 14]

Execution time: 0.0 seconds


In [27]:
print(arr**2)
print([x**2 for x in lst ])

[ 4  1 36  9 81]
[1, 4, 9, 16, 25]


In [16]:
print(np.mean(arr))
print(sum(lst)/len(lst))

4.2
3.0


In [18]:
#even filter
print(arr[arr%2==0])
print([x for x in lst if x%2==0])

[2 6]
[2, 4]


In [21]:
#2D data
print(np.array([[2,3],[4,5]]))
print([[1,2],[7,8]])

[[2 3]
 [4 5]]
[[1, 2], [7, 8]]


In [22]:
#Add two
a=np.array([1,2,3])
b=np.array([7,8,9])
a+b

array([ 8, 10, 12])

In [23]:
a=[4,5,6]
b=[3,4,5]
print([x+y for x,y in zip(a,b)])

[7, 9, 11]


In [28]:
#BROADCASTING
print(arr+1)
#broadcasting not available in list

[ 3  2  7  4 10]


In [29]:
#conditional replace
arr[arr>2]=0
print(arr)

[2 1 0 0 0]


In [32]:
lst=[1,2,3,4]
# list comprehension [val if cond else val for element in list]
print([0 if x>2 else x for x in lst])

[1, 2, 0, 0]


In [34]:
#creatig array : provide list , or direct nums, arrange , linspace 
#np.arange(start,end,step) # end is exclusive
arr=np.arange(0,10,2) 
arr

array([0, 2, 4, 6, 8])

In [37]:
#np.linspace(start,end,count)
arr=np.linspace(0,100,5)# 5 is not step its no. of elements
arr

array([  0.,  25.,  50.,  75., 100.])

In [38]:
#float behavior
arr=np.arange(0,1,0.2)
arr

array([0. , 0.2, 0.4, 0.6, 0.8])

In [41]:
arr=np.linspace(0,1,6)
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [43]:
#endpoint cotrol
print("\n linspace without endpoint")
print(np.linspace(0,10,5,endpoint=False))


 linspace without endpoint
[0. 2. 4. 6. 8.]


In [44]:
#Lenght comparison
print("\n number of elements")
print("len(arange):",len(np.arange(0,10,2)))
print("len(linspace):",len(np.linspace(0,10,5)))


 number of elements
len(arange): 5
len(linspace): 5


In [45]:
# Precision demonstration
print("Precision check")
arr=np.arange(0,1,0.1)
lin=np.linspace(0,1,10)
print("arr",arr)
print("lin",lin)

Precision check
arr [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
lin [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [54]:
#Array filtering
arr = np.arange(55,65)
print(arr)

[55 56 57 58 59 60 61 62 63 64]


In [55]:
mask = arr>59
print("\ncondition (arr > 58):\n",mask)


condition (arr > 58):
 [False False False False False  True  True  True  True  True]


In [56]:
# step 4: filtered values
filtered =  arr[mask]
print("\nfiltered values (>59):\n", filtered)


filtered values (>59):
 [60 61 62 63 64]


In [57]:
# Direct filtering
print(arr[arr>59])

[60 61 62 63 64]


In [58]:
# multiple condition
print(arr[(arr>59) & (arr<63)])

[60 61 62]


In [60]:
# students marks
marks = np.array([62,32,76,35,89])
passed_boolean = marks>35
print(passed_boolean)
print(marks[passed_boolean])

[ True False  True False  True]
[62 76 89]


In [68]:
# shallow copy vs Deep copy
a = np.array([10,20,30,40,50,60])
b= a[0:6]
b[0]=1000  # modify original array

In [69]:
a

array([1000,   20,   30,   40,   50,   60])

In [70]:
# Deep copy
c = a.copy()
c

array([1000,   20,   30,   40,   50,   60])

In [71]:
c[0]=15

In [72]:
a # intact- no change

array([1000,   20,   30,   40,   50,   60])

In [73]:
c # only c get modified

array([15, 20, 30, 40, 50, 60])